context:
  name: wigglystuff
  version: "0.2.24"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 4586fa7edd1e629de3c16a5f545336a3ecbd2fc89ee3764848ab9289e3cab521

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - anywidget >=0.9.2
    - numpy
    - pillow

tests:
  - python:
      imports:
        - wigglystuff
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://koaning.github.io/wigglystuff/
  summary: 'A collection of creative AnyWidgets for Python notebook environments.'
  description: |
    The project uses anywidget under the hood so our tools should work in Jupyter, Shiny for Python, VSCode, Colab, Solara and Marimo. Because of the anywidget integration you should also be able interact with ipywidgets natively.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/koaning/wigglystuff

extra:
  recipe-maintainers:
    - claudiushaag
