context:
  name: wigglystuff
  version: "0.2.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 464010cac6fb0a36fa844ef7578794b3f2d9b22430d4ffc8003d7dffb7c9028a

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - altair >=6.0.0
    - anywidget >=0.9.2
    - mohtml >=0.1.11
    - numpy
    - pillow

tests:
  - python:
      imports:
        - wigglystuff
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://koaning.github.io/wigglystuff/
  summary: 'A collection of creative AnyWidgets for Python notebook environments.'
  description: |
    The project uses anywidget under the hood so our tools should work in Jupyter, Shiny for Python, VSCode, Colab, Solara and Marimo. Because of the anywidget integration you should also be able interact with ipywidgets natively.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/koaning/wigglystuff

extra:
  recipe-maintainers:
    - claudiushaag
