context:
  name: wigglystuff
  version: "0.2.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 33cf54ccc241e733017be90a4538dcbe9d64251ce77c15179f17362c3624a16b

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - altair >=6.0.0
    - anywidget >=0.9.2
    - mohtml >=0.1.11
    - numpy
    - pillow

tests:
  - python:
      imports:
        - wigglystuff
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://koaning.github.io/wigglystuff/
  summary: 'A collection of creative AnyWidgets for Python notebook environments.'
  description: |
    The project uses anywidget under the hood so our tools should work in Jupyter, Shiny for Python, VSCode, Colab, Solara and Marimo. Because of the anywidget integration you should also be able interact with ipywidgets natively.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/koaning/wigglystuff

extra:
  recipe-maintainers:
    - claudiushaag
